import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme/provider";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <main className="w-full h-[calc(100%-10%)] mt-[10%]">
            <h1 className="text-white text-[14px] font-[700] mb-[20px]">Back</h1>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
